version: '3'

services:

  nodeapp:
    build:
      context: node
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    tty: true
    volumes:
      - ./node:/usr/src/app/
    networks:
      - node2-network
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: node index.js

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: dbnode
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=roor
    networks:
      - node2-network

  nginx:
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - node2-network
    ports:
      - "8080:80"
    depends_on:
      - db

networks:
  node2-network:
    driver: bridge